spring:
  application:
    name: SpringCamelActiveMQ_Testing
  datasource:
    url: jdbc:mysql://localhost:3306/SpringCamel
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
management:
  endpoints:
    web:
      exposure:
        include: camelroutes
  endpoint:
    camelroutes:
      enbaled: true
